root = "."
tmp_dir = "tmp"

[build]
  cmd = "go build -o ./tmp/server.exe ./cmd/server"
  bin = "tmp/server.exe"
  include_ext = ["go"]
  exclude_dir = ["tmp", "bin", "migrations"]
  delay = 200

[log]
  time = false

[misc]
  clean_on_exit = true
